index:
    path: /
    controller: App\Controller\DefaultController::index

verif_code_page:
    path: /verif-code
    controller: App\Controller\CodeController::enterCode

app_charts_details:
    path: /charts/
    controller: App\Controller\ChartsController::test
    methods: GET
